//! Client identity: the UA is generated by official default_client code; fingerprint
//! segments are runtime-overridable via the anchored patches —
//! version: CCODEX_CODEX_VERSION (runtime-version-override patch), defaulting to the
//! compile-time baked upstream version.
//! OS/terminal segments: CCODEX_UA_* (ua-fingerprint-env-override patch);
//! ua_platform = "windows" (default) writes the fixed Windows fingerprint,
//! ua_platform = "native" writes nothing and lets official dynamic detection run
//! (official Linux persona).

use crate::config::IdentityConfig;

/// Upstream version baked at compile time from vendor/.ccodex-sync.json (resolved by the
/// sync script).
pub const BAKED_CODEX_VERSION: &str = env!("CCODEX_BAKED_VERSION");

const DEFAULT_UA_OS_TYPE: &str = "Windows";
const DEFAULT_UA_OS_VERSION: &str = "10.0.26200";
const DEFAULT_UA_ARCH: &str = "x86_64";
const DEFAULT_UA_TERMINAL: &str = "WindowsTerminal/1.21";

/// Computes the UA env vars to write (pure function for testability).
/// Returns (var, value, is_explicit_user_config). native mode emits only explicitly
/// configured segments; windows mode fills missing segments with the Windows fingerprint.
fn ua_env_plan(cfg: &IdentityConfig) -> Vec<(&'static str, String, bool)> {
    let native = cfg.ua_platform.as_deref() == Some("native");
    let fields: [(&'static str, Option<&str>, &str); 4] = [
        (
            "CCODEX_UA_OS_TYPE",
            cfg.ua_os_type.as_deref(),
            DEFAULT_UA_OS_TYPE,
        ),
        (
            "CCODEX_UA_OS_VERSION",
            cfg.ua_os_version.as_deref(),
            DEFAULT_UA_OS_VERSION,
        ),
        ("CCODEX_UA_ARCH", cfg.ua_arch.as_deref(), DEFAULT_UA_ARCH),
        (
            "CCODEX_UA_TERMINAL",
            cfg.ua_terminal.as_deref(),
            DEFAULT_UA_TERMINAL,
        ),
    ];
    fields
        .into_iter()
        .filter_map(|(var, explicit, default)| {
            explicit
                .map(str::to_string)
                .or(if native {
                    None
                } else {
                    Some(default.to_string())
                })
                .map(|value| (var, value, explicit.is_some()))
        })
        .collect()
}

pub fn apply(cfg: &IdentityConfig) {
    // config > explicit env var > compile-time baked upstream version
    let version: String = cfg
        .version
        .clone()
        .or_else(|| std::env::var("CCODEX_CODEX_VERSION").ok())
        .unwrap_or_else(|| BAKED_CODEX_VERSION.to_string());
    // SAFETY: single-threaded init phase.
    unsafe { std::env::set_var("CCODEX_CODEX_VERSION", &version) };

    if BAKED_CODEX_VERSION == "0.0.0" {
        tracing::warn!(
            "未烘焙上游版本号（vendor/.ccodex-sync.json 缺少 codex_version），请重新运行 sync_upstream.py"
        );
    }

    if let Some(originator) = &cfg.originator
        && let Err(e) = codex_login::default_client::set_default_originator(originator.clone())
    {
        tracing::warn!("originator 设置失败，回退官方默认 codex_cli_rs: {e:?}");
    }

    for (var, value, explicit) in ua_env_plan(cfg) {
        if !explicit && std::env::var(var).is_ok() {
            continue; // Defaults never override explicit env vars.
        }
        // SAFETY: single-threaded phase before the tokio runtime starts.
        unsafe { std::env::set_var(var, value) };
    }

    tracing::info!(
        version = version,
        user_agent = codex_login::default_client::get_codex_user_agent(),
        originator = codex_login::default_client::originator().value,
        "upstream client identity"
    );
}

/// The version header (Provider default header) shares the UA's version.
pub fn codex_version() -> String {
    std::env::var("CCODEX_CODEX_VERSION").unwrap_or_else(|_| BAKED_CODEX_VERSION.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg(platform: Option<&str>) -> IdentityConfig {
        IdentityConfig {
            ua_platform: platform.map(str::to_string),
            ..Default::default()
        }
    }

    #[test]
    fn windows_mode_fills_all_defaults() {
        let plan = ua_env_plan(&cfg(None));
        assert_eq!(plan.len(), 4);
        assert!(plan.contains(&("CCODEX_UA_OS_TYPE", "Windows".to_string(), false)));
        assert!(plan.contains(&(
            "CCODEX_UA_TERMINAL",
            "WindowsTerminal/1.21".to_string(),
            false
        )));
        // Explicit "windows" is the same as the default.
        assert_eq!(ua_env_plan(&cfg(Some("windows"))).len(), 4);
    }

    #[test]
    fn native_mode_writes_nothing_by_default() {
        assert!(ua_env_plan(&cfg(Some("native"))).is_empty());
    }

    #[test]
    fn native_mode_still_honors_explicit_fields() {
        let mut c = cfg(Some("native"));
        c.ua_terminal = Some("gnome-terminal/3.52".to_string());
        let plan = ua_env_plan(&c);
        assert_eq!(
            plan,
            vec![(
                "CCODEX_UA_TERMINAL",
                "gnome-terminal/3.52".to_string(),
                true
            )]
        );
    }
}
